### ISSUE TITLE
Support for multi-GPU configuration

### ISSUE THREAD

**Issue by kiwhite** [Hekstra-Lab/careless#37]
On a node with multiple GPUs allocated, I get `ValueError: Memory growth cannot differ between GPU devices`. This can be bypassed by allocating only a single GPU, but a solution for specifying device ID would be useful.

**Comment by kmdalton** [comment]
can you try running two instances of `careless` simultaneously with the `--disable-memory-growth` flag set, and report back here?

thanks.

**Comment by kiwhite** [comment]
Setting `--disable-memory-growth` works. Alternatively, `CUDA_VISIBLE_DEVICES=0 careless ...` can be used to explicitly run on device 0.

**Comment by kmdalton** [comment]
@kiwhite is of the opinion that `careless` should accept a command line parameter for GPU device number (int).

**Comment by kmdalton** [comment]
the following snippet may be helpful as a workaround: 
```python
    gpus = tf.config.experimental.list_physical_devices('GPU')
    assert gpus
    if len(gpus) > 1:
        print('Found multiple GPUs:\n{}\nRunning on device 0.'.format(gpus))
        tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
```

**Comment by kmdalton** [comment]
@kiwhite -- should i disable memory growth by default? i can flip the parameter to `--enable-memory-growth`

**Comment by kmdalton** [comment]
i think this is resolved in the `experimental` branch by 4fe8420c38014e314c93b21ba988f0d62b7ca36c which adds a `--gpu-id` command line argument. does @kiwhite agree?

**Comment by kiwhite** [comment]
@kmdalton looks like it's working, I think that did it!

**Comment by kmdalton** [comment]
okay -- i will close this issue then. thanks.
