### ISSUE TITLE
Unexpected keyword argument 'check_isomorphous'

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/careless#55]
![image](https://user-images.githubusercontent.com/35602603/179379919-5d2a3b97-2748-46ff-88ad-c1b123be44e0.png)

running the current version of the experimental branch

**Comment by DHekstra** [comment]
Rolling back reciprocalspaceship to v0.10.0 does the trick for now.

**Comment by JBGreisman** [comment]
Up-to-date `rs` versions do not have an `append()` command because it is in the process of being deprecated in pandas. To my knowledge, we updated `careless` to remove all calls to `DataSet.append()`. 

Do you mind updating this with the latest commit in the `careless` version you're running? (You can run `git log` in the careless repo and post the output)

**Comment by DHekstra** [comment]
I am using the double-wilson material and so running on the experimental branch, I'm guessing that it is far enough behind the main branch to cause this problem?

**Comment by JBGreisman** [comment]
not necessarily #46 updated the experimental branch,  which was later merged into the main branch. If you post your `git log` output, we'll be able to assess the situation a bit more.

**Comment by kmdalton** [comment]
I can confirm, #46 removed the offending call to `append`. If you update to the latest `experimental` or `main`, It will resolve this error. Double-Wilson is also available in `main` now. 

I would like to close this issue, because I think it pertains to a stale version. Feel free to re-open it, if you feel that's wrong, @DHekstra.

**Comment by DHekstra** [comment]
The following still produces the error:

```
pip install git+https://github.com/Hekstra-Lab/careless.git@experimental
pip install reciprocalspaceship --upgrade
```

the latter command gives me v 0.10.2 of `rs` but results in the error I started this issue with. rolling back reciprocalspaceship to v 0.10.0 solves it.

**Comment by kmdalton** [comment]
there is absolutely no `append` call in [line 78 of `careless.io.formatter`](https://github.com/Hekstra-Lab/careless/blob/8f72fecfa32968c3806dae3177b471fc86248cba/careless/io/formatter.py#L78) in the experimental branch. 

i see two possible interpretations:
 1)  this is a subtly different error. if so please paste the traceback here
 2) you are still using a stale branch somehow.

**Comment by DHekstra** [comment]
`Traceback (most recent call last):
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-2/bin/careless", line 8, in <module>
    sys.exit(main())
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-2/lib/python3.8/site-packages/careless/careless.py
", line 7, in main
    run_careless(parser)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-2/lib/python3.8/site-packages/careless/careless.py
", line 28, in run_careless
    inputs,rac = df.format_files(parser.reflection_files)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-2/lib/python3.8/site-packages/careless/io/formatte
r.py", line 124, in format_files
    return self((load(f) for f in files))
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-2/lib/python3.8/site-packages/careless/io/formatte
r.py", line 101, in __call__
    data, rac = self.get_data_and_asu_collection(datasets)
  File "/n/home12/dhekstra/miniconda3/envs/careless-dw-2/lib/python3.8/site-packages/careless/io/formatte
r.py", line 78, in get_data_and_asu_collection
    data = data.append(ds, check_isomorphous=False)
TypeError: append() got an unexpected keyword argument 'check_isomorphous'
`

**Comment by kmdalton** [comment]
yeah i'm afraid the offending line should not exist if you are up to date. try a fresh conda env and/or add the `--upgrade` flag.

**Comment by DHekstra** [comment]
OK, a clean conda env resolved the issue (using the experimental branch).
