### ISSUE TITLE
[Feature Request] Add commandline flag for repeated cross-validation

### ISSUE THREAD

**Issue by JBGreisman** [Hekstra-Lab/careless#6]
The recent change in the `experimental` branch implementation of cross-validation fits the scaling weights based on the full set of input reflections, and then evaluates the half-datasets using the fixed model (akin to how cross-validation is implemented in AIMLESS and most conventional crystallography suites). This provides an opportunity to assess the uncertainties in half-dataset correlations by repeated partitioning of half-datasets -- I've found this to be useful in some cases for better assessing measurements like [`CCanom`](https://hekstra-lab.github.io/reciprocalspaceship/examples/2_mergingstats.html#Summary).

I think this could be implemented using a commandline flag such as `--num-xval`, which takes an integer and defaults to `1`. I think the output should still have the usual 3 files (full merged, half1 merged, half2 merged), but the half-datasets can include an additional column, `sample`, which denotes which repeat of cross-validation the merged structure factor amplitudes resulted from. This output format will facilitate downstream `groupby` operations for analysis in `reciprocalspaceship`.

Proposed output format for each half-dataset:
|  H  | K    | L    | F(+) | SigF(+) | F(-) | SigF(-) | N(+) | N(-) | sample |
| --- | --- | --- | ---- | -------- | -----| ------|-------|-----|--------|
|  h1   |  k1| l1   | 1.1    | 0.1          | 1.2  |    0.2   |  10      | 11    | 1           |
|  h1   |  k1| l1   | 1.3    | 0.2         | 1.1  |    0.3   |  19      | 13   | 2           |
|  h2  |  k2| l2  | 1.2    | 0.2          | 1.3  |    0.1   |  10      | 11    | 1           |
|  h2   |  k2| l2   | 1.1    | 0.1          | 1.2  |    0.2   |  10      | 11    | 2          |
| ... |

**Comment by kmdalton** [comment]
Given the rewrite in [experimental](https://github.com/Hekstra-Lab/careless/tree/experimental), this is now much easier to implement. Is this still a desirable feature? I just wanted to note that because of completeness, you won't necessarily get the same miller indices in each `sample`. Is that an issue? @JBGreisman

**Comment by kmdalton** [comment]
Should I stop outputing `[out]_half{1,2}_[file_id].mtz` and instead just make a single `[out]_xval.mtz` with `half`, `file_id`, and `sample` columns?

**Comment by JBGreisman** [comment]
I'm not sure this feature is necessary anymore. It is something that I sometimes use in order to assess the uncertainty in half-dataset correlation coefficients, but it doesn't seem like something that would be broadly useful to users. 

Regarding the other comment, I personally prefer the single `[out]_xval.mtz` style. It allows for computing correlation coefficients with just 3-4 lines of `pandas` methods. But I also don't feel too strongly about this either.

**Comment by kmdalton** [comment]
I will 
 - add a `--half-dataset-repeats` flag into the crossvalidation arguments group to take care of repeated half dataset merging
 - switch half dataset output to a single `_xval.mtz` file with integer `file_id` and `repeat` columns
 - output a single `_predictions.mtz` with `Iobs`, `SigIobs`, `Ipred` as well as `file_id` and `test` columns where `test` is 0 or 1 to indicate training vs test set. 
 
 Do you have any bandwidth this week to write a quick IPython notebook for training diagnostics, @JBGreisman?

**Comment by kmdalton** [comment]
This is certainly resolved by c9771f4a92918ffcfecc2c9cb70d721b3ac7a874 over in the experimental. I'm going to go ahead and close this issue now.
