### ISSUE TITLE
confusing careless -h wording

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/careless#63]
In the CLI help output, the following wording seems confusing. I imagine this is an option meant for a scenario analogous to the transfer learning case for scales. "weights" seems confusing, and it is not clear what the user is meant to provide

`--structure-factor-file STRUCTURE_FACTOR_FILE
                        Weights file from a previous careless run to initialize the structure factors. This should be a string beginning with the [output_base] from a previous run (ie 'merge/hewl_structure_factor').` 

I can't think of an immediate use case I'd be interested in, so not high priority as far as I'm concerned.

**Comment by kmdalton** [comment]
Is this more clear?

```  --structure-factor-file STRUCTURE_FACTOR_FILE
                        Initialize the structure factors from the ouput of a
                        previous run. This argument should be a string
                        beginning with the base filename used in the previous
                        run and ending in _structure_factor.  For instance, if
                        the previous run was called with `careless mono [...]
                        merge/hewl`, the appropriate filename to use would be
                        merge/hewl_structure_factor.
```

**Comment by DHekstra** [comment]
yes, great.
