### ISSUE TITLE
`rs` / `gemmi` installation issue

### ISSUE THREAD

**Issue by dennisbrookner** [Hekstra-Lab/careless#66]
Hey team,

I recently created a new conda environment and installed `careless` into it. `careless` successfully installed the `reciprocalspaceship` dependency, but did **not** install `gemmi`. I eventually solved the issue by explicitly installing `reciprocalspaceship==0.9.16`, which brought `gemmi==0.4.9` along with it.

I am raising this issue here, rather than on `reciprocalspaceship` directly, because I was unable to reproduce the issue by creating a fresh environment and installing `reciprocalspaceship`. It seems that however `rs` (and @JBGreisman) is handling version control and staying up to date with `gemmi`, `careless` was unable to interface with it properly?

I think that any examples I try to provide will be inevitably poisoned by what is cached in my local and/or cluster conda installations, so I will not do that and instead just leave it to others to get to the bottom of this.

**Comment by kmdalton** [comment]
Can you provide the commands you used to install careless? Does this happen from a fresh miniconda installation?

I was not personally able to reproduce this issue.

**Comment by kmdalton** [comment]
Any thoughts about this @JBGreisman or @dennisbrookner? My inclination is to close this issue. I think it is most likely something pathological in @dennisbrookner 's conda install.

**Comment by kmdalton** [comment]
(or pathology in the cluster filesystem)

**Comment by JBGreisman** [comment]
I'm also unable to reproduce any issues with `reciprocalspaceship` and `gemmi` when installing `careless`. I think this is likely a specific environment issue--perhaps there were some packages installed into the base environment or cached that were causing issues?

**Comment by dennisbrookner** [comment]
Yeah this can definitely be closed, I don't think this is a real issue. I'll circle back if I learn anything more concrete.

This probably wasn't helping...
```
==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.9.0
```
