### ISSUE TITLE
Selectively merge groups of outputs

### ISSUE THREAD

**Issue by dennisbrookner** [Hekstra-Lab/careless#68]
Hey all, excited to be a new `careless` user. I have been exploring the various flags and options available, and I see that it is possible to use the `--separate-files` flag to control whether the inputs get merged together or separately. However, it would be nice to be able to merge files selectively. E.g., if you have four files
 - `off_pass1`
 - `off_pass2`
 - `200ns_pass1`
 - `200ns_pass2`

you would then add some flag like `--groups=0,0,1,1` (or even `--separate-files=0,0,1,1` ?) to specify which files get merged together. If I am understanding correctly, this is not currently possible, but it seems like a fairly straightforward extension of the existing functionality.

A more complicated iteration of this could also exist making clever use of the double-Wilson priors. In the mean time, though, just a `--groups` flag would be a really nice improvement.

**Comment by JBGreisman** [comment]
I'll let @kmdalton assess whether this is a worthwhile addition to the API, but in the meantime this behavior can always be achieved with some pre-processing of your "grouped" MTZs. For example, you can concatenate your `off` MTZs together and adjusting the BATCH (or related metadata) to make sure the values are meaningful.

**Comment by kmdalton** [comment]
It had always been my intention for users to accomplish this by combining MTZs upstream in `rs`. I'm open to implementing it, but I have to note I don't have much bandwidth. I probably won't have time to implement this feature before the holidays. It'll require thinking about corner cases like non-isomorphism. Just being realistic. 

I'm not really a `careless` pro-user tbh. So I don't know how important this feature request is. Maybe @DHekstra should weigh in.

**Comment by dennisbrookner** [comment]
> adjusting the BATCH (or related metadata) to make sure the values are meaningful

I think this is the part that I was missing - I should be able to get this more or less working. I'll also defer to @DHekstra as to whether to close this issue or keep mulling on it, but I think I'm satisfied for the time being. Thanks!

**Comment by DHekstra** [comment]
I think we can close this for now. In general, I think it would be helpful for users to have some examples of upstream rs manipulations that achieve these things. Regardless, it doesn't warrant modifications to Careless at this time.

**Comment by kmdalton** [comment]
i'll close this for now. would not be opposed to @dennisbrookner committing some examples to careless-examples along these lines.
