### ISSUE TITLE
graph execution error/libdevice not found

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/careless#72]
When running Careless on the thermolysin example data with (attached) settings, I encounter the following graph execution error (attached).
[slurm_script.txt](https://github.com/Hekstra-Lab/careless/files/9861095/slurm_script.txt)

[myoutput_30592150_err.txt](https://github.com/Hekstra-Lab/careless/files/9861081/myoutput_30592150_err.txt)

**Comment by kmdalton** [comment]
i'm pretty sure this is a python config issue on your end. i have encountered this before. try making a new conda env and reinstalling. 

```bash
conda create -n careless python=3.10
conda activate careless
pip install --upgrade pip
pip install careless
```

**Comment by kmdalton** [comment]
Based on my test, this was an issue with the TensorFlow 2.11 release candidate. I modified `setup.py` in #73 such that it should no longer install release candidates for TF. So, I did a new [release](https://github.com/Hekstra-Lab/careless/releases/tag/v0.2.4) to distribute this change. Let me know if this fixes your issue.

**Comment by DHekstra** [comment]
yes, it works now!
